#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY  (0 | (0 << 8))
#define MAP_LITTLEROOT_TOWN (1 | (0 << 8))
#define MAP_OLDALE_TOWN     (2 | (0 << 8))
#define MAP_ROUTE101        (3 | (0 << 8))
#define MAP_ROUTE102        (4 | (0 << 8))
#define MAP_ROUTE103        (5 | (0 << 8))
#define MAP_TWINLEAF_TOWN   (6 | (0 << 8))
#define MAP_ROUTE201        (7 | (0 << 8))
#define MAP_LAKE_VERITY     (8 | (0 << 8))
#define MAP_SANDGEM_TOWN    (9 | (0 << 8))
#define MAP_ROUTE202        (10 | (0 << 8))
#define MAP_ROUTE203        (11 | (0 << 8))
#define MAP_ROUTE204        (12 | (0 << 8))
#define MAP_OREBURGH_GATE   (13 | (0 << 8))
#define MAP_RAVAGED_PATH    (14 | (0 << 8))
#define MAP_JUBILIFE_CITY   (15 | (0 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))
#define MAP_TWINLEAF_TOWN_DAWNS_HOUSE_2F         (5 | (1 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (3 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (3 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (3 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (3 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (3 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (3 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (3 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (4 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (4 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (4 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (4 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (4 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (4 << 8))
#define MAP_TRADE_CENTER             (25 | (4 << 8))
#define MAP_RECORD_CORNER            (26 | (4 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (4 << 8))
#define MAP_INSIDE_OF_TRUCK          (28 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (29 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (30 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (31 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (32 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (33 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (34 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (35 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (36 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (37 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (38 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (39 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (40 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (41 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (42 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (43 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (44 | (4 << 8))
#define MAP_UNION_ROOM               (45 | (4 << 8))

// gMapGroup_SpecialArea
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (0 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (1 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (2 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (3 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (4 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (5 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (6 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (7 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (8 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (9 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (10 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (11 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (12 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (13 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (14 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (15 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (16 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (17 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (18 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (19 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (20 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (21 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (22 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (23 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (24 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (25 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (26 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (27 | (5 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (28 | (5 << 8))

#define MAP_GROUPS_COUNT 6

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
