@Menu
Poketch_Menu_Text::
	.string "Switching on...\p"
    .string "Which app do you want to launch?$"

Poketch_Exit_Text::
    .string "Switching off..$"

@Time Changer
Poketch_TimeChanger_TxtStartup_Day::
    .string "Daylight Ditty is currently playing.\p"
    .string "Would you like to change the song?$"

Poketch_TimeChanger_TxtStartup_Night::
    .string "Starlight Sonata is currently playing.\p"
    .string "Would you like to change the song?$"

Poketch_Time_TxtDay::
    .string "Now playing Daylight Ditty.\p"
    .string "Daytime Pokemon will now show up.$"

Poketch_Time_TxtNight::
    .string "Now playing Starlight Sonata.\p"
    .string "Nighttime Pokemon will now show up.$"

@Day-Care Checker
Poketch_DCA_TxtStartup::
	.string "Launching the Daycare Checker\p"
	.string "Welcome to the Daycare Checker!\p"
	.string "Would you like to check on your Pokémon?$"

Poketch_DCA_TxtEggWaiting::
	.string "Checking...\p"
	.string "From Day Care Man:\n"
	.string "Hello!\p" 
	.string "We have an egg waiting here for you!\p"
	.string "Please come pick it up at your earliest\n"
	.string "convenience.$"

Poketch_DCA_TxtEggNone::
	.string "Checking...\p"
	.string "From Day Care Man:\n"
	.string "Hello!\p" 
	.string "Sorry, We don't have an egg for you\n" 
	.string "at this time.$"

@Frienship Checker
Poketch_FCA_Txt_Startup::
    .string "Analyzing friendship. . .$"

FCA_Txt_NONE::
	.string "Zzt!? Your Pokémon simply detests you!\p"
	.string "The things it says scares even me!$"

FCA_Txt_1_TO_49::
	.string "It seems a bit distant.\p"
	.string "Maybe its time for a little more\n"
	.string "bonding, zzrt!$"

FCA_Txt_50_TO_99::
	.string "Its warming up to you!\p"
	.string "Keep up the good work, trainer!$"

FCA_Txt_100_TO_149::
	.string "Your Pokémon is feeling quite\n"
	.string "friendly now.\p"
	.string "You two make a good team, zzt!$"

FCA_Txt_150_TO_199::
	.string "Zzrt! It clearly loves being with you!\p"
	.string "What an amazing bond you share, zzt!$"

FCA_Txt_200_TO_254::
	.string "Your Pokémon only speaks highly of you!\p"
	.string "It obviously likes you a lot, zzrt!$"

FCA_Txt_MAX::
	.string "You and your Pokémon are inseparable!\p"
	.string "You're the best of friends, now and\n"
	.string "forever, zzt zzt!$"
